import type { Metadata } from 'next'

import './globals.css'
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import Providers from "@/components/providers";

export const metadata: Metadata = {
  title: 'ירקונה',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="he">
      <body>
      <header>
          <Providers>
              <Navbar/>
          </Providers>
      </header>
      {children}
      <footer className={'fixed bottom-0 w-full'}>
        <Footer/>
      </footer>
      </body>
    </html>
  )
}
